services:
  - type: web
    name: printing-ustad-web
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm run start"
    healthCheckPath: "/api/health"
    autoDeploy: true
