// Hierarchical category structure for Navigation & Shop browsing
export const CATEGORY_GROUPS = [
  {
    id: 'apparel',
    name: 'Apparel & Clothing',
    shortName: 'Apparel',
    icon: 'checkroom',
    description: 'Custom t-shirts, hoodies, polos, caps & aprons',
    slugs: ['t-shirts', 'hoodies', 'polo-shirts', 'caps', 'aprons'],
  },
  {
    id: 'drinkware',
    name: 'Mugs & Drinkware',
    shortName: 'Drinkware',
    icon: 'local_cafe',
    description: 'Personalized coffee mugs, drinkware & coasters',
    slugs: ['mugs', 'drinkware', 'coasters'],
  },
  {
    id: 'tech',
    name: 'Tech & Mobile',
    shortName: 'Tech & Mobile',
    icon: 'devices',
    description: 'Custom phone cases, mousepads & laptop sleeves',
    slugs: ['phone-cases', 'mousepads', 'laptop-sleeves'],
  },
  {
    id: 'stationery',
    name: 'Stationery & Office',
    shortName: 'Stationery',
    icon: 'menu_book',
    description: 'Visiting cards, notebooks, pens, calendars & badges',
    slugs: ['visiting-cards', 'diaries', 'pens', 'calendars', 'badges'],
  },
  {
    id: 'home-decor',
    name: 'Home & Living',
    shortName: 'Home & Decor',
    icon: 'chair',
    description: 'Custom cushions, wall clocks & photo frames',
    slugs: ['cushions', 'wall-clocks', 'photo-frames'],
  },
  {
    id: 'accessories',
    name: 'Jewelry & Accessories',
    shortName: 'Accessories',
    icon: 'diamond',
    description: 'Engraved rings, custom keychains & tote bags',
    slugs: ['rings', 'keychains', 'tote-bags'],
  },
  {
    id: 'corporate',
    name: 'Corporate & Awards',
    shortName: 'Corporate Gifts',
    icon: 'card_giftcard',
    description: 'Corporate gifts, crystal awards & trophies',
    slugs: ['corporate-gifts', 'awards'],
  },
];

export const DEFAULT_SUBCAT_NAMES = {
  't-shirts': 'T-Shirts',
  'hoodies': 'Hoodies & Sweatshirts',
  'polo-shirts': 'Polo Shirts',
  'caps': 'Caps & Headwear',
  'aprons': 'Aprons',
  'mugs': 'Mugs',
  'drinkware': 'Bottles & Drinkware',
  'coasters': 'Coasters',
  'phone-cases': 'Phone Cases',
  'mousepads': 'Mousepads',
  'laptop-sleeves': 'Laptop Sleeves',
  'diaries': 'Notebooks & Diaries',
  'pens': 'Pens',
  'visiting-cards': 'Visiting Cards',
  'calendars': 'Calendars',
  'badges': 'Badges & Lanyards',
  'cushions': 'Cushions & Pillows',
  'wall-clocks': 'Wall Clocks',
  'photo-frames': 'Photo Frames',
  'rings': 'Rings & Jewelry',
  'keychains': 'Keychains',
  'tote-bags': 'Tote Bags',
  'corporate-gifts': 'Corporate Gift Sets',
  'awards': 'Awards & Trophies',
};

// Subcategory display metadata (icon, popular badge)
export const SUBCATEGORY_META = {
  't-shirts': { icon: 'styler', popular: true },
  'hoodies': { icon: 'dry_cleaning', popular: true },
  'polo-shirts': { icon: 'apparel' },
  'caps': { icon: 'sports_baseball' },
  'aprons': { icon: 'soup_kitchen' },
  'mugs': { icon: 'coffee', popular: true },
  'drinkware': { icon: 'water_bottle' },
  'coasters': { icon: 'crop_square' },
  'phone-cases': { icon: 'smartphone', popular: true },
  'mousepads': { icon: 'mouse' },
  'laptop-sleeves': { icon: 'laptop' },
  'diaries': { icon: 'book', popular: true },
  'pens': { icon: 'edit' },
  'visiting-cards': { icon: 'badge', popular: true },
  'calendars': { icon: 'calendar_today' },
  'badges': { icon: 'id_card' },
  'cushions': { icon: 'airline_seat_individual_suite' },
  'wall-clocks': { icon: 'schedule' },
  'photo-frames': { icon: 'photo_frame' },
  'rings': { icon: 'diamond', popular: true },
  'keychains': { icon: 'vpn_key', popular: true },
  'tote-bags': { icon: 'shopping_bag' },
  'corporate-gifts': { icon: 'card_giftcard', popular: true },
  'awards': { icon: 'military_tech' },
};
